"""empty message

Revision ID: 18231f07a46a
Revises: 
Create Date: 2026-01-03 17:38:31.228878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18231f07a46a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('foundation_year', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=75), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('property',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('property_type', sa.Enum('HOUSE', 'APARTMENT', 'COMMERCIAL', 'LAND', name='propertytypeenum'), nullable=False),
    sa.Column('short_description', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('property_value', sa.DECIMAL(), nullable=False),
    sa.Column('square_meter', sa.DECIMAL(), nullable=False),
    sa.Column('rooms_amount', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('property_status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'RENTED', 'RESERVED', name='propertystatusenum'), nullable=False),
    sa.Column('owner_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_id'), 'property', ['id'], unique=True)
    op.create_table('address',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=30), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('house_number', sa.String(length=15), nullable=False),
    sa.Column('apartment_number', sa.String(length=10), nullable=True),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('property_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_id'), 'address', ['id'], unique=True)
    op.create_table('lease',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rent_amount', sa.DECIMAL(), nullable=False),
    sa.Column('initial_deposit_amount', sa.DECIMAL(), nullable=False),
    sa.Column('renewal_accepted', sa.Boolean(), nullable=False),
    sa.Column('lease_expired', sa.Boolean(), nullable=False),
    sa.Column('lease_expiration_date', sa.Date(), nullable=True),
    sa.Column('billing_period', sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', name='billingperiodenum'), nullable=False),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.String(length=50), nullable=True),
    sa.Column('property_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['user.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lease_id'), 'lease', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lease_id'), table_name='lease')
    op.drop_table('lease')
    op.drop_index(op.f('ix_address_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_property_id'), table_name='property')
    op.drop_table('property')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
