"""empty message

Revision ID: 24dbe8ca3c8b
Revises: dc3c860ada60
Create Date: 2024-08-26 15:12:29.389857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dbe8ca3c8b'
down_revision = 'dc3c860ada60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('description', table_name='property')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('description', 'property', ['description'], unique=False)
    # ### end Alembic commands ###
