"""empty message

Revision ID: 53368bcb5eb5
Revises: 
Create Date: 2024-08-26 12:37:07.147611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53368bcb5eb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
