"""empty message

Revision ID: 5abfcbc2f425
Revises: 797429e6d34a
Create Date: 2024-08-31 21:05:55.410804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abfcbc2f425'
down_revision = '797429e6d34a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('stripe_charge_id', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('waiting_for_payment', sa.Boolean(), nullable=False),
    sa.Column('payment_accepted', sa.Boolean(), nullable=False),
    sa.Column('payment_checkout_url', sa.String(length=500), nullable=True),
    sa.Column('lease_id', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['user.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
