"""empty message

Revision ID: 797429e6d34a
Revises: 
Create Date: 2024-08-29 12:58:53.600630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797429e6d34a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lease',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rent_amount', sa.DECIMAL(), nullable=False),
    sa.Column('initial_deposit_amount', sa.DECIMAL(), nullable=False),
    sa.Column('renewal_accepted', sa.Boolean(), nullable=False),
    sa.Column('lease_expired', sa.Boolean(), nullable=False),
    sa.Column('lease_expiration_date', sa.Date(), nullable=True),
    sa.Column('billing_period', sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', name='billingperiodenum'), nullable=False),
    sa.Column('next_payment_date', sa.Date(), nullable=False),
    sa.Column('payment_bank_account', sa.String(length=75), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.String(length=50), nullable=True),
    sa.Column('property_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['user.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lease_id'), 'lease', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lease_id'), table_name='lease')
    op.drop_table('lease')
    # ### end Alembic commands ###
