"""empty message

Revision ID: b0b8d503ec5a
Revises: 24dbe8ca3c8b
Create Date: 2024-08-26 19:03:28.657510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b8d503ec5a'
down_revision = '24dbe8ca3c8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('foundation_year', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=True)
    op.add_column('user', sa.Column('company_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'], onupdate='cascade', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'company_id')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
