"""empty message

Revision ID: b4415881a1ca
Revises: 
Create Date: 2025-12-07 12:30:23.610043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4415881a1ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'role_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_name', mysql.VARCHAR(length=50), server_default=sa.text("'user'"), nullable=False))
    op.add_column('user', sa.Column('role_id', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
