"""empty message

Revision ID: d5090582a336
Revises: 
Create Date: 2024-09-01 10:53:31.776070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5090582a336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lease', 'next_payment_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lease', 'next_payment_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
