"""empty message

Revision ID: d80fa343d471
Revises: 53368bcb5eb5
Create Date: 2024-08-26 12:52:33.414091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80fa343d471'
down_revision = '53368bcb5eb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
