"""empty message

Revision ID: dc3c860ada60
Revises: d80fa343d471
Create Date: 2024-08-26 14:35:39.939244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3c860ada60'
down_revision = 'd80fa343d471'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
