"""empty message

Revision ID: e9e84e2c11e3
Revises: b0b8d503ec5a
Create Date: 2024-08-27 09:06:23.853259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e84e2c11e3'
down_revision = 'b0b8d503ec5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
